### ISSUE TITLE
Vraag

### ISSUE THREAD

**Issue by wvanbreukelen** [BasvdW22/Zermelo-WhatsApp-Bot#1]
Zou het mogelijk zijn om tester van de bot te worden?

Zo ja, gegevens per mail uitwisselen lijkt mij het handigste.

**Comment by BasvdW22** [comment]
Sure, anders gewoon gegevens uitwisselen via Telegram, iets gemakkelijker.

**Comment by wvanbreukelen** [comment]
Ook goed :+1:
